trigger:
  branches:
    include:
    - '*'
    exclude:
    - l10n
    - dependabot/*

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      yarn install
    displayName: 'install dependencies'

  - script: |
      yarn lerna run --ignore share-we-go-icons --parallel --scope "share-we-go-*" build
    displayName: 'build share-we-go-ui packages'

  - script: |
      cd packages/share-we-go-ui/build
      npm version 0.0.0-canary.$(Build.SourceVersion) --no-git-tag-version
      npm pack
      mv share-we-go-ui-0.0.0-canary.$(Build.SourceVersion).tgz ../../../share-we-go-ui.tgz
    displayName: 'create share-we-go-ui canary distributable'

  - task: S3Upload@1
    inputs:
      regionName: 'eu-central-1'
      bucketName: 'eps1lon-share-we-go-ui'
      globExpressions: '*.tgz'
      targetFolder: 'artifacts/$(Build.SourceBranchName)/$(Build.SourceVersion)'
      filesAcl: 'public-read'
    displayName: "Upload distributables to S3"
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    env:
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

  - task: PublishPipelineArtifact@0
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'canaries'
      targetPath: 'share-we-go-core.tgz'

  - script: |
      yarn web-app:build
    displayName: 'build web-app'

  - script: |
      yarn size:snapshot
    displayName: 'create a size snapshot'

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'size-snapshot'
      targetPath: 'scripts/sizeSnapshot/build/stats.json'

  - script: |
      node scripts/sizeSnapshot/upload
    displayName: 'persist size snapshot'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    env:
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

  - script: |
      yarn danger ci
    displayName: 'run danger on PRs'
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
    env:
      DANGER_GITHUB_API_TOKEN: $(GITHUB_API_TOKEN)
