files:
  - source: /web-app/src/**/*.md
    ignore:
      - /**/%file_name%-%two_letters_code%.md
      - /web-app/src/pages/getting-started/templates/*/**/*
      - /web-app/src/pages/premium-themes/*/**/*
    translation: /%original_path%/%file_name%-%two_letters_code%.%file_extension%
  - source: /web-app/translations/*.json
    ignore:
      - /**/%file_name%-%two_letters_code%.json
    translation: /%original_path%/%file_name%-%two_letters_code%.%file_extension%
